# Numpy==> karesh ba arraye(Numerical python)-2005-kar ba matris fogholadas-nesbat be pandas emkanat kamtar darad- ta jaiy ke cpu mizare az hamon pandas estefade konid-4 amaliat asli- karbordi dar big data

# importing libraries

In [1]:
import numpy as np

# difference between lists and arrays

In [2]:
import time

In [3]:
num_list=list(range(1,10**8))
num_arrays=np.arange(1,10**8)

In [4]:
start1=time.time()
sum(num_list)
stop1=time.time()

In [5]:
stop1-start1

2.842768430709839

In [6]:
start2=time.time()
num_arrays.sum()
end2=time.time()

In [7]:
end2-start2

0.06578326225280762

# creating arrays

In [9]:
lst=[1,2,3,4,5]
print(lst)
arr1=np.array(lst)
arr1

[1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

In [10]:
arr2=np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [11]:
#arraye 2bodi
array2d=([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    
])
array2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
arr3=np.arange(2,10)
arr3

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr4=np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr5=np.arange(10,21,3)
arr5

array([10, 13, 16, 19])

In [22]:
arr6=np.arange(24).reshape(2,3,4)
arr6

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
type(arr6)

numpy.ndarray

# beroz resani==>updating==>maghadir ghabele taghir bashand

In [24]:
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [25]:
array1[2]=20
array1

array([ 1,  2, 20,  4,  5])

In [27]:
array1[1:4]=3
array1

array([1, 3, 3, 3, 5])

# taghire abaad

In [31]:
numbers=np.arange(10)
numbers.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
numbers.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# abaade yek array

In [39]:
numbers2=np.arange(10)
numbers2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
len(numbers2) #tedad deraye ha dar tak bodi va dar 2 bodi tedad satre

10

In [43]:
numbers2.shape# abaade shomara midahad

(10,)

In [44]:
numbers2.size # tedad eleman

10

In [46]:
numbers2.ndim

1

### array2d

In [47]:
array10=np.arange(6).reshape(2,3)
array10

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
len(array10)

2

In [49]:
array10.shape

(2, 3)

In [50]:
array10.size

6

In [51]:
array10.ndim

2

In [53]:
print(array10.shape[0])
print(array10.shape[1])

2
3


# tabdile list be arraye

In [55]:
lst1=[1,2,3,4,5,6]
arr1=np.array(lst1)
arr1

array([1, 2, 3, 4, 5, 6])

In [57]:
# pish pardazeshi
lst2d=[[1,2,3],[4,5,6]]
arr2d=np.asarray(lst2d)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
lst2d2=[[1,2,3],[4,5,6]]
arr2d2=np.array(lst2d2)
arr2d2

array([[1, 2, 3],
       [4, 5, 6]])

# array haiy ba maghadire sabet==> jabre khati

In [62]:
arrzero=np.zeros((3,4),dtype="int32")
arrzero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
# tamame maghadir yek bashand
arrone=np.ones((2,3))
arrone

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
arr_three=np.full((5,4),3)
arr_three

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [ ]:
# matris hamani==> deraye haye ghotre asli yek baghie sefr

In [68]:
# matris hamani
arr_eye=np.eye(3)
arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.linspace(1,4,num=8) # az adad yek ta 4 be 8 ghesmat taghsim kon

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [70]:
random1=np.random.random(3) # tak bodi  be tedadi ke shoma migoid
random1

array([0.02867235, 0.44090572, 0.56120145])

In [73]:
random2=np.random.randint(10,100) # beine 0 ta 10 yeki mide
random2

78

In [74]:
random3=np.random.random((2,3))
random3

array([[0.31912397, 0.80689291, 0.84807843],
       [0.03027776, 0.45680424, 0.48521595]])

In [75]:
random4=np.random.randint(1,20,4)
random4

array([11, 10, 10, 11])

In [76]:
random5=np.random.randint(1,20,(2,3))
random5

array([[ 4,  1,  4],
       [16,  3,  5]])

In [77]:
# tozie yeknavakhte gosaste  tasadofi
random6=np.random.rand(5)
random6

array([0.35265705, 0.67951468, 0.16605961, 0.57299985, 0.96617042])

In [79]:
#tozie  normale standard, miangin 0 vas varianse yek
random7=np.random.randn(4)
random7

array([-0.8208795 , -1.10369616, -1.57577061,  1.03194129])

In [80]:
random8=np.random.normal() # (miangin,enheraf meyar)
random8

-0.42919001676320817

# tavabea amade

min
max
mean
sum
mnedian
std

In [82]:
randomi=np.random.randint(1,100,(3,4))
randomi

array([[27, 29, 89, 25],
       [90, 47, 46,  8],
       [24, 37, 51, 18]])

In [83]:
np.max(randomi)

90

In [84]:
np.min(randomi,axis=0)

array([24, 29, 46,  8])

In [85]:
np.argmax(randomi,axis=1)

array([2, 0, 2], dtype=int64)

In [86]:
np.std(randomi)

24.807452957170398

In [87]:
np.mean(randomi,axis=1)

array([42.5 , 47.75, 32.5 ])

In [88]:
np.std(randomi,axis=0)

array([30.43024811,  7.36357401, 19.20069443,  6.97614985])

In [89]:
np.sum(randomi,axis=0)

array([141, 113, 186,  51])

In [90]:
np.sum(randomi)

491

In [91]:
np.mean(randomi)

40.916666666666664

# indexes==>dastresi be deraye ha

In [92]:
number10=np.random.randint(1,100,(3,4))
number10

array([[80,  3, 55, 39],
       [53, 34, 57, 37],
       [12, 89, 29, 91]])

In [93]:
number10[1,2] # satre 1 sotone 2

57

In [95]:
number10[0:2,:]

array([[80,  3, 55, 39],
       [53, 34, 57, 37]])

In [98]:
number10[0:2,1:3]

array([[ 3, 55],
       [34, 57]])

In [99]:
number10[:,2:]

array([[55, 39],
       [57, 37],
       [29, 91]])

# ijade halghe baraye indexing

In [100]:
number5=np.random.randint(1,100,(3,4))
number5

array([[24, 70, 35, 26],
       [20, 26, 70,  2],
       [89, 30, 49, 70]])

In [101]:
for row in number5:
    print(row)

[24 70 35 26]
[20 26 70  2]
[89 30 49 70]


In [103]:
for row in number5:
    for r in row:
        print(r)

24
70
35
26
20
26
70
2
89
30
49
70


# flat==> reshape mikonad va takht mikonad arraye hara==> 1bodi

In [105]:
for row in number5.flat:
    print(row*2)

48
140
70
52
40
52
140
4
178
60
98
140


# tavabea riazi

In [108]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)

In [109]:
x

array([[1., 2.],
       [3., 4.]])

In [110]:
y

array([[5., 6.],
       [7., 8.]])

In [111]:
x.T # transpose=>taranehade

array([[1., 3.],
       [2., 4.]])

In [112]:
x>2

array([[False, False],
       [ True,  True]])

In [113]:
x+1

array([[2., 3.],
       [4., 5.]])

In [114]:
x[x>2]

array([3., 4.])

In [115]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [116]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [117]:
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [118]:
np.pi

3.141592653589793

# flatten

In [120]:
x2=x.flatten()
x2

array([1., 2., 3., 4.])

In [121]:
y2=y.flatten()
y2

array([5., 6., 7., 8.])

In [122]:
x2.dot(y2) # zarbe dakheli

70.0

In [123]:
np.dot(x2,y2)

70.0

In [124]:
np.matmul(x2,y2) # zarbe khareji

70.0

In [125]:
x

array([[1., 2.],
       [3., 4.]])

In [126]:
y

array([[5., 6.],
       [7., 8.]])

In [127]:
np.matmul(x,y) # zarbe matris ha

array([[19., 22.],
       [43., 50.]])

In [128]:
np.linalg.det(x) #determinane matrise x

-2.0000000000000004

In [129]:
x3=np.array([[1,2],[3,4]])
y3=np.array([[4,5],[6,7]])
x3

array([[1, 2],
       [3, 4]])

In [130]:
y3

array([[4, 5],
       [6, 7]])

In [132]:
print(np.add(x3,y3))

[[ 5  7]
 [ 9 11]]


In [133]:
print(np.subtract(x3,y3))

[[-3 -3]
 [-3 -3]]


In [134]:
x3*y3

array([[ 4, 10],
       [18, 28]])

In [135]:
print(np.multiply(x3,y3))

[[ 4 10]
 [18 28]]


In [136]:
x

array([[1., 2.],
       [3., 4.]])

In [137]:
y

array([[5., 6.],
       [7., 8.]])

# aggregate  kardan ==> kenare ham gharar dadan

In [138]:
x

array([[1., 2.],
       [3., 4.]])

In [139]:
y

array([[5., 6.],
       [7., 8.]])

In [140]:
np.hstack((x,y))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [141]:
np.vstack((x,y))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [142]:
np.concatenate((x,y))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

# yek bodi sazi

In [144]:
array20=np.array([(1,2),(3,4),(5,6),(7,8)])
array20

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [145]:
array20.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [146]:
array20.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

# cophy kardan

# 1)copy na mostaghel

In [149]:
a1=np.array([1,2,3,4,5])
a2=a1
print(a1)
print(a2)
a1[2]=100
a2[3]=20
print(a1)
print(a2)

[1 2 3 4 5]
[1 2 3 4 5]
[  1   2 100  20   5]
[  1   2 100  20   5]


# 2) na mostaghel

In [150]:
a1=np.array([1,2,3,4,5])
a3=np.copy(a1)
print(a1)
print(a3)
a1[2]=100
a3[3]=20
print(a1)
print(a3)

[1 2 3 4 5]
[1 2 3 4 5]
[  1   2 100   4   5]
[ 1  2  3 20  5]


# append/det elements==> ezafe kardan ya pak kardane deraye

In [3]:
numbers1=np.array([20,30,40,50,60])
numbers1=np.append(numbers1,[70,80])
print(numbers1)

[20 30 40 50 60 70 80]


In [5]:
numbers1=np.delete(numbers1,2)
print(numbers1)

[20 30 70 80]


In [7]:
import numpy as np
numbers1=np.delete(numbers1,[2,3])
print(numbers1)

[20 30]


# broadcasting

In [8]:
z1=np.array([1,2,3])
z2=np.array([[1,2,3],[4,5,6],[7,8,9]])
z3=z1+z2
z3
# bayad compatible ya sazgar bashand

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

# save/load arrays

In [10]:
n1=np.array([1,2,3,4])
np.save(r"E:\projects\numpy-class\numpy1.npy",n1)

In [11]:
loading=np.load(r"E:\projects\numpy-class\numpy1.npy")
print(loading)

[1 2 3 4]


In [12]:
type(loading)

numpy.ndarray